### ISSUE TITLE
apa102 led

### ISSUE THREAD

**Issue by Vroqzy** [Drumber/RemoteLight#1]
does this work with apa102 ledstrip

connected on a raspberry pi 3b

**Comment by Drumber** [comment]
Hi, the current version supports only WS2812 based LEDs. But I will add support for Apa102 LED strips in the next release.

**Comment by Drumber** [comment]
You can now set Apa102 as strip type in the config.properties of the latest [RemoteLightServer release](https://github.com/Drumber/RemoteLightServer/releases).
But I couldn't test the functionality because I don't have such LED strip.

**Comment by Vroqzy** [comment]
Wow thats fast :)
gonna try to setup everything i keep you updated

**Comment by Drumber** [comment]
SPI error fixed and tested, color bug will be fixed soon.
Release: https://github.com/Drumber/RemoteLightServer/releases/tag/pre0.2.0.3
