### ISSUE TITLE
ws2811_init failed: Hardware revision is not supported

### ISSUE THREAD

**Issue by SethThMc** [Drumber/RemoteLight#12]
When I try to Activate my Raspberry Pi from the GUI on my Windows PC, I get this error:

ws2811_init failed: Hardware revision is not supported
[09:30:10] [ERROR] java.lang.RuntimeException: Error initialising the WS281x strip
	at com.diozero.ws281xj.rpiws281x.WS281x.<init>(WS281x.java:172)
	at com.diozero.ws281xj.rpiws281x.WS281x.<init>(WS281x.java:151)
	at de.lars.remotelightserver.utils.StripTypeUtil.getLedDriverInterface(StripTypeUtil.java:112)
	at de.lars.remotelightserver.Main.createPixelController(Main.java:108)
	at de.lars.remotelightserver.server.Server$1.run(Server.java:85)
	at java.base/java.lang.Thread.run(Thread.java:834)

When I Ctrl + C to kill the program, this is what gets spit out:

^C>> Closing...

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x7541c624, pid=2235, tid=2261

 JRE version: OpenJDK Runtime Environment (11.0.7+10) (build 11.0.7+10-post-Raspbian-3deb10u1)
 Java VM: OpenJDK Server VM (11.0.7+10-post-Raspbian-3deb10u1, mixed mode, g1 gc, linux-)
 Problematic frame:
 C  [libws281xj15647745924769448261.so+0x2624]  ws2811_fini+0xc

 No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /home/pi/hs_err_pid2235.log
[09:30:33] [INFO] [Server] Server stopped...

 If you would like to submit a bug report, please visit:
   Unknown
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

Aborted

I am using a Raspberry Pi 4B 4Gb, and I am using the 2.0.4 version files for both the Raspberry Pi and my PC.

**Comment by Drumber** [comment]
Thanks for reporting the error. Apparently there was a problem with the support of your Raspberry Pi model. I have updated to the latest Diozero library version, that should fix it.

Would be awesome if you could test the snapshot build before I release it and tell me if the error is fixed.
Snapshot build: [RemoteLightServer-pre0.2.0.5-SNAPSHOT.jar.zip](https://github.com/Drumber/RemoteLight/files/5584813/RemoteLightServer-pre0.2.0.5-SNAPSHOT.jar.zip)

**Comment by SethThMc** [comment]
When I run the new snapshot .jar, I get:

pi@raspberrypi:~ $ sudo java -jar RemoteLightServer-pre0.2.0.5-SNAPSHOT.jar
Error: Invalid or corrupt jarfile RemoteLightServer-pre0.2.0.5-SNAPSHOT.jar

**Comment by Drumber** [comment]
Have you unzipped the jar file?

**Comment by SethThMc** [comment]
Sorry, I downloaded it again it it worked fine. It must have been a bad download, i don't really know. It works fine now! Thanks for your help!
