### ISSUE TITLE
Problem with Trident Z RGB 

### ISSUE THREAD

**Issue by Taziur** [Drumber/RemoteLight#17]
Hi im new here and i have a problem with trident z leds. When i use music sync >Energy one module light start from bottom and the second one from top (video) how to make it both start from one side ?
Trident Z RGB , MSI B450 Gaming max plus

https://user-images.githubusercontent.com/79856782/109515897-e54ba880-7aa7-11eb-904b-32746097d912.mp4

**Comment by Drumber** [comment]
Hi, this behaviour is intended. Most of RemoteLight's effects are designed for 1-dimensional LED strips and so is the Energy visualizer: the 'energy bar' is centered on the strip and thus the left and right sides are mirrored.

However, you could clone the output to make both RAM sticks look identical, (if you don't care that both will show exactly the same effects and animations). You can enable the output clone patch in the settings of the output.
I also made a short video to show you how it works.

https://user-images.githubusercontent.com/29163322/109697012-fff84d00-7b8d-11eb-86a5-d62eed7b0599.mp4

**Comment by Taziur** [comment]
Works for me, Thank you very much !
