### ISSUE TITLE
Auto enable last effect in settings

### ISSUE THREAD

**Issue by BangDroid** [Drumber/RemoteLight#22]
I am finding the Auto enable last effect checkbox in settings is not enabling ScreenColor effect on relaunch. I must manually enable it each time.

0.2.5-beta

This is really cool btw, loving the integration with OpenRGB. Very glad to be rid of Asus crap

**Comment by Drumber** [comment]
Hi, ScreenColor is indeed not yet activated automatically. I will add it and leave this issue open until then.

**Comment by BangDroid** [comment]
Okay cool

**Comment by Drumber** [comment]
Added the feature, you can download the latest build from here: https://remotelight.github.io/
